echo 'Descargando paquetes...'
sudo apt-get update
sudo apt-get -y install \
	autoconf \
	automake \
	build-essential \
	checkinstall \
	cmake \
	doxygen \
	gfortran \
	git \
	graphviz \
	imagemagick \
	libasound2-dev \
	libass-dev \
	libatlas-base-dev \
	libavcodec-dev \
	libavdevice-dev \
	libavfilter-dev \
	libavformat-dev \
	libavutil-dev \
	libcurl4-openssl-dev \
	libdc1394-22-dev \
	libfontconfig1-dev \
	libfreetype6-dev \
	libgl1-mesa-dev \
	libgmp-dev \
	libgstreamer1.0-dev \
	libgstreamer-plugins-base1.0-dev \
	libgtk-3-dev \
	libhdf5-103 \
	libhdf5-dev \
	libjack-jackd2-dev \
	libjansson-dev \
	libjasper-dev \
	libjpeg-dev \
	liblapacke-dev \
	libluajit-5.1-dev \
	libmbedtls-dev \
	libmp3lame-dev \
	libopencore-amrnb-dev \
	libopencore-amrwb-dev \
	libopenexr-dev \
	libopus-dev \
	libpng-dev \
	libpulse-dev \
	libqt4-test \
	libqt5svg5-dev \
	libqt5x11extras5-dev \
	libqtgui4 \
	libqtwebkit4 \
	librtmp-dev \
	libsdl2-dev \
	libsdl2-image-dev \
	libsdl2-mixer-dev \
	libsdl2-net-dev \
	libsdl2-ttf-dev \
	libsnappy-dev \
	libsoxr-dev \
	libspeexdsp-dev \
	libssh-dev \
	libssl-dev \
	libswresample-dev \
	libswscale-dev \
	libtiff-dev \
	libtool \
	libudev-dev \
	libv4l-dev \
	libva-dev \
	libvdpau-dev \
	libvlc-dev \
	libvo-amrwbenc-dev \
	libvorbis-dev \
	libwebp-dev \
	libx11-dev \
	libx11-xcb1 \
	libx11-xcb-dev \
	libx265-dev \
	libxcb1-dev \
	libxcb-randr0 \
	libxcb-randr0-dev \
	libxcb-shape0-dev \
	libxcb-shm0-dev \
	libxcb-xfixes0 \
	libxcb-xfixes0-dev \
	libxcb-xinerama0-dev \
	libxcb-xinput0 \
	libxcb-xinput-dev \
	libxcomposite-dev \
	libxinerama-dev \
	libxml2-dev \
	libxvidcore-dev \
	lzma-dev \
	meson \
	nasm \
	pkg-config \
	python3-dev \
	python3-numpy \
	python3-pip \
	python3-pyqt5 \
	qtbase5-dev \
	qtbase5-private-dev \
	swig \
	texinfo \
	wget \
	yasm \
	zlib1g-dev